### ISSUE TITLE
Can not install latest pcl via homebrew & dyld: Library not loaded: /usr/local/lib/libflann_cpp.1.8.dylib

### ISSUE THREAD

**Issue by LuZhouheng** [antimodular/ofxPCL#1]
## Environment:
* macOS 10.12.1
* Xcode 8.2
* OF 0.9.8

## Console

```ruby
dyld: Library not loaded: /usr/local/lib/libflann_cpp.1.8.dylib
  Referenced from: /usr/local/opt/pcl/lib/libpcl_features.1.7.dylib
  Reason: image not found
```

## Install Error

```ruby
$ brew install pcl
Updating Homebrew...
==> Installing pcl from homebrew/science
==> Installing dependencies for homebrew/science/pcl: cminpack, qhull, glew, libpng, freetype, fontconfig, jpeg, libtiff, vtk
==> Installing homebrew/science/pcl dependency: cminpack
==> Downloading http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.gz

curl: (7) Failed to connect to devernay.free.fr port 80: Operation timed out
Error: Failed to download resource "cminpack"
Download failed: http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.gz
```

I can not install latest version of plc, search for it but still can not install? How can you install the latest version? And I have the similar build error in your gist: 
https://gist.github.com/antimodular/75abe99baacb3aee0dab#gistcomment-1727264.

**Comment by stephanschulz** [comment]
i remember having problems with the newest pcl when installing everything on a fresh computer.
i do have https://github.com/antimodular/ofxPCL/blob/master/lib_172.zip that you could try to use.
but i gave up for now on pcl.

**Comment by LuZhouheng** [comment]
Thanks very much, I'll try it.
